# Generated by Django 5.2.6 on 2025-09-25 08:36

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='کد محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='apparel_images/main/', verbose_name='تصویر اصلی')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('مشکی', 'مشکی'), ('سفید', 'سفید'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('سبز', 'سبز'), ('زرد', 'زرد'), ('نارنجی', 'نارنجی'), ('بنفش', 'بنفش'), ('صورتی', 'صورتی'), ('قهوه\u200cای', 'قهوه\u200cای'), ('خاکستری', 'خاکستری'), ('کرم', 'کرم'), ('طلایی', 'طلایی'), ('نقره\u200cای', 'نقره\u200cای'), ('آبی تیره', 'آبی تیره'), ('سبز تیره', 'سبز تیره'), ('قرمز تیره', 'قرمز تیره'), ('بژ', 'بژ'), ('فیروزه\u200cای', 'فیروزه\u200cای'), ('یاسی', 'یاسی')], max_length=30, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='کد رنگ هگزا', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('بچگانه', 'بچگانه')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'جنسیت',
                'verbose_name_plural': 'جنسیت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='KidsGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('پسرانه', 'پسرانه'), ('دخترانه', 'دخترانه'), ('نوزاد', 'نوزاد'), ('مشترک', 'مشترک (پسرانه/دخترانه)')], max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'جنسیت بچگانه',
                'verbose_name_plural': 'جنسیت\u200cهای بچگانه',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('نخی', 'نخی'), ('پشمی', 'پشمی'), ('ابریشمی', 'ابریشمی'), ('کتان', 'کتان'), ('پلی\u200cاستر', 'پلی\u200cاستر'), ('ویسکوز', 'ویسکوز'), ('لایکرا', 'لایکرا'), ('جین', 'جین'), ('کردروی', 'کردروی'), ('مخمل', 'مخمل'), ('چرم', 'چرم'), ('چرم مصنوعی', 'چرم مصنوعی'), ('کشمیر', 'کشمیر'), ('فلیس', 'فلیس'), ('نایلون', 'نایلون'), ('رایون', 'رایون'), ('کرپ', 'کرپ'), ('ژاکارد', 'ژاکارد'), ('ترگال', 'ترگال'), ('مخلوط', 'مخلوط')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'جنس',
                'verbose_name_plural': 'اجناس',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('تی\u200cشرت', 'تی\u200cشرت'), ('بلوز', 'بلوز'), ('شلوار', 'شلوار'), ('مانتو', 'مانتو'), ('کاپشن', 'کاپشن'), ('شورت', 'شورت'), ('زیرپوش', 'زیرپوش'), ('جوراب', 'جوراب'), ('چادر', 'چادر'), ('روسری', 'روسری'), ('مقنعه', 'مقنعه'), ('سرهمی', 'سرهمی'), ('پیراهن', 'پیراهن'), ('دامن', 'دامن'), ('کت', 'کت'), ('ژاکت', 'ژاکت'), ('هودی', 'هودی'), ('سوئیشرت', 'سوئیشرت'), ('تونیک', 'تونیک'), ('شومیز', 'شومیز'), ('لگ', 'لگ'), ('شلوارک', 'شلوارک'), ('کفش', 'کفش'), ('کتانی', 'کتانی'), ('صندل', 'صندل'), ('لباس زیر', 'لباس زیر'), ('کلاه', 'کلاه'), ('کیف', 'کیف'), ('کمربند', 'کمربند')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصول',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='slideshow_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('کلاسیک', 'کلاسیک'), ('اسپرت', 'اسپرت'), ('رسمی', 'رسمی'), ('کژوال', 'کژوال'), ('مدرن', 'مدرن'), ('وینتیج', 'وینتیج'), ('بوهو', 'بوهو'), ('مینیمال', 'مینیمال'), ('شیک', 'شیک'), ('جوانانه', 'جوانانه'), ('کودکانه', 'کودکانه'), ('فانتزی', 'فانتزی'), ('ساده', 'ساده'), ('طرح\u200cدار', 'طرح\u200cدار'), ('اتنیک', 'اتنیک'), ('گلدوزی', 'گلدوزی'), ('چاپی', 'چاپی'), ('یقه\u200cدار', 'یقه\u200cدار'), ('بدون آستین', 'بدون آستین'), ('آستین بلند', 'آستین بلند')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'سبک',
                'verbose_name_plural': 'سبک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ApparelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apparel_images/multiple/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('apparel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nafis.apparel')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='nafis.attributetype')),
            ],
        ),
        migrations.AddField(
            model_name='apparel',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='nafis.attributevalue'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nafis.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='apparel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apparels', to='nafis.category'),
        ),
        migrations.AddField(
            model_name='apparel',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.color', verbose_name='رنگ'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('apparel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='nafis.apparel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
            },
        ),
        migrations.AddField(
            model_name='apparel',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.gender', verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='apparel',
            name='kids_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nafis.kidsgender', verbose_name='جنسیت بچگانه'),
        ),
        migrations.CreateModel(
            name='KidsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.kidsgender')),
            ],
        ),
        migrations.AddField(
            model_name='apparel',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nafis.material', verbose_name='جنس'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('در حال پردازش', 'در حال پردازش'), ('ارسال شده', 'ارسال شده'), ('تحویل شده', 'تحویل شده'), ('لغو شده', 'لغو شده')], default='در حال پردازش', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.AddField(
            model_name='apparel',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.producttype', verbose_name='نوع محصول'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('apparel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.apparel')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nafis.order')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.size')),
            ],
        ),
        migrations.AddField(
            model_name='apparel',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.style', verbose_name='سبک'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('apparel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='nafis.apparel', verbose_name='محصول')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.color', verbose_name='رنگ')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار',
                'unique_together': {('apparel', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apparel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.apparel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nafis.size')),
            ],
            options={
                'unique_together': {('user', 'apparel', 'size', 'color')},
            },
        ),
    ]
