# Generated by Django 5.2.6 on 2025-09-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='announcement_images/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='apparel',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='kidssubcategory',
            name='gender',
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'موجودی انبار', 'verbose_name_plural': 'موجودی\u200cهای انبار'},
        ),
        migrations.AlterField(
            model_name='apparel',
            name='code',
            field=models.CharField(blank=True, help_text='این فیلد به صورت خودکار تولید می\u200cشود.', max_length=10, unique=True, verbose_name='کد محصول'),
        ),
        migrations.RemoveField(
            model_name='apparel',
            name='color',
        ),
        migrations.AlterField(
            model_name='apparel',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nafis.producttype', verbose_name='نوع محصول'),
        ),
        migrations.RemoveField(
            model_name='apparel',
            name='style',
        ),
        migrations.AlterField(
            model_name='kidsgender',
            name='name',
            field=models.CharField(choices=[('پسرانه', 'پسرانه'), ('دخترانه', 'دخترانه'), ('نوزاد پسر', 'نوزاد پسر'), ('نوزاد دختر', 'نوزاد دختر'), ('مشترک', 'مشترک (پسرانه/دخترانه)')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='AttributeType',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='KidsSubCategory',
        ),
        migrations.AddField(
            model_name='apparel',
            name='color',
            field=models.ManyToManyField(blank=True, to='nafis.color', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='apparel',
            name='style',
            field=models.ManyToManyField(blank=True, to='nafis.style', verbose_name='سبک'),
        ),
    ]
