# Generated by Django 5.2.10 on 2026-02-07 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, help_text='شناسه محصول (برای تطبیق آینده با جدول محصولات)', null=True)),
                ('design_data', models.JSONField(default=dict, help_text='\n        ساختار طراحی: {\n          "version": 1,\n          "items": [\n            {"image": "...", "x": 0, "y": 0, "scale": 1, "rotation": 0, "z": 0}\n          ],\n          "activeItemIndex": 0,\n          "uvSize": 2048\n        }\n        ')),
                ('preview_image', models.ImageField(blank=True, help_text='تصویر پیش\u200cنمایش PNG', null=True, upload_to='designs/previews/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طراحی',
                'verbose_name_plural': 'طراحی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
